name: OodleBaDoodle
favicon: null
layout_spectrum: 0.5053706
typography_spectrum: 0.8688756350893527
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E1E1DF'
    - '#80775B'
    - '#393A39'
    - '#0D6591'
    - '#169BBD'
  brandStrength: 1
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0.6600429
purpose: []
