analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0.6278195
  lightness: 0.1638023
  brandColors:
    - '#E1E1DF'
    - '#80775B'
    - '#393A39'
    - '#0D6591'
    - '#169BBD'
  rhythmicContrast: 0.6600429
typography_spectrum: 0.8688756350893527
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5053706
favicon: null
name: OodleBaDoodle
